### ISSUE TITLE
overriding settings with CLI arguments

### ISSUE THREAD

**Issue by BorePlusPlus** [tes/conflab#2]
According to documentation any command line arguments user passes are overriden by any settings in config files and/or JSON. This is the opposite of how I am used to seeing config libraries work. From experience most of the time when user passes something as a CLI arg he/she wants to apply it as an override.

>This will load configuration from the following sources, with the later files over-riding any values set in the earlier ones (think of it as getting more specfic as you go down the list).
>
>argv params (--database.host db.example.com)
>./config/default.json
>./config/[environment>].json
>./config/runtime.json
>./config/[your-hostname].json
>etcd:/conflab/service-name/_etcd/environment/config**

**Comment by cliftonc** [comment]
Thanks - was probably due to lack of sleep in SF when I originally put this together :)
