### ISSUE TITLE
Add a way for users to include additional config files

### ISSUE THREAD

**Issue by BorePlusPlus** [tes/conflab#4]
Sometimes users can have additional config files which are not held in the same directory as the rest of the files (often these are files containing restricted options).

One of the ways to include these could be to have a "reserved field" in the config files which would signify that file(s) it points to should be read and merged in config. This way users can decide at what point the additional file is merged (by referring to it in appropriate file). This is a bit like [reader macros in nomad](https://github.com/james-henderson/nomad#nomad-reader-macros).

If these files are indeed restricted files which contents you might not want to share with the whole world, having an option of not exporting their contents into etcd might also be required (maybe through a "reserved field" in these files).

Example:
default.json
```json
{
  "foo": "bar",
  "additionalConfigFiles": ["/etc/stuff/passes.json"]
}
``` 
/etc/stuff/passes.json
```json
{
  "exportToEtcd": false,
  "secret": "goes here"
}
```
This would read passes.json after default.json and merge the results into config, but not export them to etcd.

**Comment by BorePlusPlus** [comment]
It would probably be a good idea if this feature could be turned on/off via opts

**Comment by cliftonc** [comment]
lgtm, but we could flip the 'exportToEtcd' to default to false, and just say that all 'additional' config files are not loaded to etcd by default and have to be explicitly enabled for it.

**Comment by BorePlusPlus** [comment]
I've committed a monstrosity on this subject - see the code for details...
