### ISSUE TITLE
BOM is not handled correctly when loading a config file and no error is thrown

### ISSUE THREAD

**Issue by PeterAronZentai** [tes/conflab#5]
Albeit useless, BOM is part of the UTF-8 specification. Conflab when reading a config file uses fs.read then a JSON.parse that fails parsing a file with BOM (you have to use strip-bom e.g.) The real pain here is that the error is swallowed at https://github.com/tes/conflab/blob/master/index.js#L237-238 

The result is that conflab fails to load a specific config step but also does not let you know about this.

**Comment by BorePlusPlus** [comment]
Since I am already digging in conflab area let me give it a spin...

**Comment by BorePlusPlus** [comment]
@cliftonc is this something cunning I don't understand or an oversight?
https://github.com/tes/conflab/blob/master/index.js#L241

**Comment by cliftonc** [comment]
No oversight, I was probably just being lazy and didn't give any thought re. what I should actually do if the parse failed.

We should strip the bom or require the file instead of load + json parse (as I suspect that require will deal with the bom naturally).

**Comment by PeterAronZentai** [comment]
I am closing this one as the actual issue is resolved. And I open a new ticket for the error handling case. I guess just shoveling in the ```err``` to ```next()``` is a breaking change since there might be systems online with a non-parseable config (but eventually it should be done some time)... as quick solution a logger.error should be enough...
