### ISSUE TITLE
Configuration file parsing errors should be receivable in err argument

### ISSUE THREAD

**Issue by PeterAronZentai** [tes/conflab#6]
At https://github.com/tes/conflab/blob/master/index.js#L241 next() is called without properly providing content for the err argument. Along with the exception object we should also pass the offending file thats name is a closure var.

```JavaScript
next(ex.sourceFile = file.path && ex); 
```

**Comment by PeterAronZentai** [comment]
I would do it myself - but still do not feel confident committing to a library without proper knowledge on the implications :)

**Comment by BorePlusPlus** [comment]
:+1:  As a user I prefer libraries that fail fast...

**Comment by cliftonc** [comment]
This change won't break anything, and if it does we will know what it is based on the clear error message and fix it.

Only libraries that use conflab are new electric ones (very few) and page composer.

**Comment by PeterAronZentai** [comment]
It is fixed, checked in and is published.
